---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(readr)
hockey_data <- read_csv("hockey_data.csv")
View(hockey_data)

hockey_data3_score <- read_csv("qianyi_score_matched_to_team.csv")
View(hockey_data3_score)
```

creating outcome, win/loss variable
```{r}
hockey_data3_score$outcome <- NA_integer_

for(i in 1:7544)
{
  if(i %% 2 != 0)
  {
    if(hockey_data3_score$score_matched_to_team[[i]] > hockey_data3_score$score_matched_to_team[[i + 1]])
    {
      hockey_data3_score$outcome[[i]] = 1
      hockey_data3_score$outcome[[(i + 1)]] = 0
    }
    else
    {
      hockey_data3_score$outcome[[i]] = 0
      hockey_data3_score$outcome[[(i + 1)]] = 1
    }
  }
}
```


```{r}
install.packages("corrplot")
library(corrplot)
correlations <- cor(hockey_data3_score$outcome ,hockey_data3_score[,c(47,48,50:79)])
corrplot(correlations, method="circle")
correlations
```

```{r}
glm.fit <- glm(outcome ~ pdo, data = hockey_data3_score)
summary(glm.fit)
plot(glm.fit)
```

```{r}
library(ggplot2)
library(tidyverse)
df_win <- hockey_data3_score[which(hockey_data3_score$outcome == 1),]
df_lose <- hockey_data3_score[which(hockey_data3_score$outcome == 0),]

df_win %>%
  ggplot(aes(sh_per, hdca_per_60)) + 
  geom_point() +
  labs(x = "Shooting Percentage", y = "High Danger Chances")

max(df_lose$sh_per)

hockey_data3_score %>%
  ggplot(aes(sh_per, sv_per)) +
  geom_point(aes(col = outcome))
```

shooting percentages
```{r}
df_win %>%
  ggplot(aes(sh_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "blue", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(sh_per, na.rm = T)),
             colour = "red", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 40, 5), labels = function(x){paste0(x, "%")}) +
  labs(x = "Shooting Percentage", y = "Density" , title = "Shooting Percentage in a Team Win")

df_lose %>%
  ggplot(aes(sh_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(sh_per, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 30, 5), labels = function(x){paste0(x, "%")}) +
  labs(x = "Shooting Percentage", y = "Density" , title = "Shooting Percentage in a Team Loss")

mean(df_win$sh_per) - mean(df_lose$sh_per)
```
high danger shooting percentage
```{r}
df_win$hdsh_per <- as.numeric(df_win$hdsh_per)
df_lose$hdsh_per <- as.numeric(df_lose$hdsh_per)

df_win %>%
  ggplot(aes(hdsh_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "blue", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(hdsh_per, na.rm = T)),
             colour = "red", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 100, 10), labels = function(x){paste0(x, "%")}) +
  labs(x = "High Danger Shooting Percentage", y = "Density" , title = " High Danger Shooting Percentage in a Team Win")

df_lose %>%
  ggplot(aes(hdsh_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(hdsh_per, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 100, 10), labels = function(x){paste0(x, "%")}) +
  labs(x = "High Danger Shooting Percentage", y = "Density" , title = "High Danger Shooting Percentage in a Team Loss")

which(is.na(df_win$hdsh_per))
mean(df_win$hdsh_per, na.rm = T) - mean(df_lose$hdsh_per, na.rm = T)
```

mid danger shooting percentage
```{r}
df_win$mdsh_per <- as.numeric(df_win$mdsh_per)
df_lose$mdsh_per <- as.numeric(df_lose$mdsh_per)

df_win %>%
  ggplot(aes(mdsh_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(mdsh_per, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 100, 10), labels = function(x){paste0(x, "%")}) +
  labs(x = "Mid Danger Shooting Percentage", y = "Density" , title = " Mid Danger Shooting Percentage in a Team Win")

df_lose %>%
  ggplot(aes(mdsh_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(mdsh_per, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 100, 10), labels = function(x){paste0(x, "%")}) +
  labs(x = "Mid Danger Shooting Percentage", y = "Density" , title = "Mid Danger Shooting Percentage in a Team Loss")

#which(is.na(df_win$hdsh_per))
mean(df_win$mdsh_per, na.rm = T) - mean(df_lose$mdsh_per, na.rm = T)
```

low danger shooting percentage
```{r}
df_win$ldsh_per <- as.numeric(df_win$ldsh_per)
df_lose$ldsh_per <- as.numeric(df_lose$ldsh_per)

df_win %>%
  ggplot(aes(ldsh_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(ldsh_per, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 100, 10), labels = function(x){paste0(x, "%")}) +
  labs(x = "Low Danger Shooting Percentage", y = "Density" , title = " Low Danger Shooting Percentage in a Team Win")

df_lose %>%
  ggplot(aes(ldsh_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(ldsh_per, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 100, 10), labels = function(x){paste0(x, "%")}) +
  labs(x = "Low Danger Shooting Percentage", y = "Density" , title = "Low Danger Shooting Percentage in a Team Loss")

#which(is.na(df_win$hdsh_per))
mean(df_win$ldsh_per, na.rm = T) - mean(df_lose$ldsh_per, na.rm = T)
```

save percentage (1 - shooting percentage)
```{r}
df_win %>%
  ggplot(aes(sv_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(sv_per, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(70, 100, 5), labels = function(x){paste0(x, "%")}) +
  labs(x = "Save Percentage", y = "Density" , title = "Save Percentage in a Team Win")

df_lose %>%
  ggplot(aes(sv_per)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(sv_per, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(60, 100, 5), labels = function(x){paste0(x, "%")}) +
  labs(x = "Shooting Percentage", y = "Density" , title = "Save Percentage in a Team Loss")
```






Shots on goal
```{r}
df_win %>%
  ggplot(aes(sf_per_60)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "blue", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(sf_per_60, na.rm = T)),
             colour = "red", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 70, 10)) +
  labs(x = "Shots For Per 60 Minutes", y = "Density" , title = "Shots For per 60 in a Team Win")

df_lose %>%
  ggplot(aes(sf_per_60)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(sf_per_60, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 70, 10)) +
  labs(x = "Shots For Per 60 Minutes", y = "Density" , title = "Shot For per 60 in a Team Loss")

mean(df_win$sf_per_60)
mean(df_lose$sf_per_60)
```

high danger shot attempts
```{r}
df_win %>%
  ggplot(aes(hdsf_per_60)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "blue", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(hdsf_per_60, na.rm = T)),
             colour = "red", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 21, 3)) +
  labs(x = "High Danger Shots For Per 60 Minutes", y = "Density" , title = "High Danger Shots For per 60 in a Team Win")

df_lose %>%
  ggplot(aes(hdsf_per_60)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(hdsf_per_60, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 21, 3)) +
  labs(x = "High Danger Shots For Per 60 Minutes", y = "Density" , title = "High Danger Shots For per 60 in a Team Loss")

mean(df_win$hdsf_per_60)
mean(df_lose$hdsf_per_60)
```

mid danger shot attempts
```{r}
df_win %>%
  ggplot(aes(mdsf_per_60)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(mdsf_per_60, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 21, 3)) +
  labs(x = "Mid Danger Shots For Per 60 Minutes", y = "Density" , title = "Mid Danger Shots For per 60 in a Team Win")

df_lose %>%
  ggplot(aes(mdsf_per_60)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(mdsf_per_60, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 21, 3)) +
  labs(x = "Mid Danger Shots For Per 60 Minutes", y = "Density" , title = "Mid Danger Shots For per 60 in a Team Loss")

mean(df_win$mdsf_per_60)
mean(df_lose$mdsf_per_60)
```

low danger shot attempts
```{r}
df_win %>%
  ggplot(aes(ldsf_per_60)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(ldsf_per_60, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 21, 3)) +
  labs(x = "Low Danger Shots For Per 60 Minutes", y = "Density" , title = "Low Danger Shots For per 60 in a Team Win")

df_lose %>%
  ggplot(aes(ldsf_per_60)) +
  geom_histogram(aes(y = ..density..), binwidth = 2, colour = "black", fill = "white") +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(aes(xintercept = mean(ldsf_per_60, na.rm = T)),
             colour = "blue", linetype ="longdash", size = .8) +
  scale_x_continuous(breaks = seq(0, 21, 3)) +
  labs(x = "Low Danger Shots For Per 60 Minutes", y = "Density" , title = "Low Danger Shots For per 60 in a Team Loss")

mean(df_win$ldsf_per_60)
mean(df_lose$ldsf_per_60)
```